// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIrig2T5Pslp6ToMb-TX9gB0JsHD_QLR0',
    appId: '1:108543268639:web:f7f6aae097a9defd0d422a',
    messagingSenderId: '108543268639',
    projectId: 'new-dr-chat-application',
    authDomain: 'new-dr-chat-application.firebaseapp.com',
    storageBucket: 'new-dr-chat-application.firebasestorage.app',
    measurementId: 'G-EESEKD7RSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvm1U7DXMoJi5FfLb4WeRiuzzBA1zesuM',
    appId: '1:108543268639:android:e43f95373006593c0d422a',
    messagingSenderId: '108543268639',
    projectId: 'new-dr-chat-application',
    storageBucket: 'new-dr-chat-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBreCYh7lHcFk0t9JUGUl2IlITVGnUBSI8',
    appId: '1:108543268639:ios:082a2d05924e477e0d422a',
    messagingSenderId: '108543268639',
    projectId: 'new-dr-chat-application',
    storageBucket: 'new-dr-chat-application.firebasestorage.app',
    iosBundleId: 'com.example.newDrChatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBreCYh7lHcFk0t9JUGUl2IlITVGnUBSI8',
    appId: '1:108543268639:ios:082a2d05924e477e0d422a',
    messagingSenderId: '108543268639',
    projectId: 'new-dr-chat-application',
    storageBucket: 'new-dr-chat-application.firebasestorage.app',
    iosBundleId: 'com.example.newDrChatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIrig2T5Pslp6ToMb-TX9gB0JsHD_QLR0',
    appId: '1:108543268639:web:e72cd37e774f5f100d422a',
    messagingSenderId: '108543268639',
    projectId: 'new-dr-chat-application',
    authDomain: 'new-dr-chat-application.firebaseapp.com',
    storageBucket: 'new-dr-chat-application.firebasestorage.app',
    measurementId: 'G-BQ26DNSQ6C',
  );
}
